(()=>{
const CLIENT_ID='37432134429-os2q3m508oljig5kqpef7d18dpjr2fif.apps.googleusercontent.com';
const API='https://aitherbackend.onrender.com';
let gisPromise;
function loadGIS(){if(window.google?.accounts?.id)return Promise.resolve();if(gisPromise)return gisPromise;gisPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.onload=resolve;s.onerror=()=>reject(new Error('Google Sign-In could not load.'));document.head.appendChild(s)});return gisPromise}
function findBodies(){return [...document.querySelectorAll('#aitherAccountBody,#aab')].filter(x=>x.offsetParent!==null&&!x.dataset.googleReady)}
async function start(){for(const body of findBodies()){const form=body.querySelector('form');if(!form)continue;body.dataset.googleReady='1';const divider=document.createElement('div');divider.style.cssText='display:flex;align-items:center;gap:10px;margin:14px 0;color:#8e98a8;font:600 11px system-ui';divider.innerHTML='<span style="height:1px;background:#ffffff18;flex:1"></span><span>OR</span><span style="height:1px;background:#ffffff18;flex:1"></span>';const wrap=document.createElement('div');wrap.style.cssText='display:grid;place-items:center;min-height:44px';wrap.innerHTML='<div class="aither-google-button"></div>';form.parentNode.insertBefore(divider,form);form.parentNode.insertBefore(wrap,form);try{await loadGIS();window.google.accounts.id.initialize({client_id:CLIENT_ID,callback:async response=>{const status=body.querySelector('.aither-account-status,.aasx,[id="aasx"]');if(status)status.textContent='Signing in with Google…';try{const r=await fetch(API+'/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({credential:response.credential})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Google sign-in failed.');if(d.session_token)localStorage.setItem('aither-session-token',d.session_token);window.AitherAccount?.refresh();window.dispatchEvent(new CustomEvent('aither:user-changed',{detail:{user:d.user}}));if(status)status.textContent='Signed in with Google.'}catch(e){if(status)status.textContent=e.message}}});window.google.accounts.id.renderButton(wrap.querySelector('.aither-google-button'),{theme:'outline',size:'large',shape:'rectangular',width:360,text:'continue_with'});}catch(e){wrap.remove();divider.remove()}}}
const observer=new MutationObserver(()=>{start().catch(()=>{})});observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>start(),{once:true});else start();
})();
